services:
  voting-app:
    build: .
    image: voting-app
    container_name: voting-app
    networks:
      - katuriy_network
    restart: unless-stopped
    ports:
      - "49981:3001"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3001
      - DB_PATH=/app/data/voting.db
      - UPLOAD_DIR=/app/data/uploads
      - JWT_SECRET=${JWT_SECRET:-change-this-secret-in-production}

networks:
  katuriy_network:
    name: katuriy_network